kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "{{meta_ipaddress}}"
nodes:
  - role: control-plane
    image: kindest/node:v1.20.15
    extraPortMappings:
      - containerPort: 5443
        hostPort: 5443
        protocol: TCP
        listenAddress: "{{meta_ipaddress}}"
